### ISSUE TITLE
Would you mind sharing the blurhash component?

### ISSUE THREAD

**Issue by Eleksar387** [paperdave/blurhash-image#1]
This component https://github.com/davecaruso/davecode.net/blob/main/src/lib/components/BlurHash.svelte mentioned in your readme doesn't seem to exist anymore. Any chance to share it? I struggle with handling the swapping of images.

**Comment by paperdave** [comment]
Sorry, that link is invalid due to my username change and also moving the component.
- It got renamed to `Img` and handles some more of my image cases, taking just a special "id", which decodes to aspect ratio + url info, [Img.svelte](https://github.com/paperdave/paperdave.net/blob/4b461f299cb87a43fa1bd828fffb6c57fc163dc4/src/lib/components/Img.svelte)
- The original component [BlurHash.svelte](https://github.com/paperdave/paperdave.net/blob/f18c382f8b9bfe81474eb637701edfeb7b9e5f4a/src/lib/components/BlurHash.svelte) before it was removed.

I made sure to make these permalinks this time, I'll update the readme with the updated link.
